### ISSUE TITLE
permissions: search

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-records-resources#61] opened 2020-08-10 11:41 UTC
How to filter fields according to permissions.

> A user might have access to restricted files or extension metadata, but other might not. however, the second might still have access to metadata. How do we filter that without leaking info (e.g. checksums, etc.).

**Comment by fenekku** [comment] 2020-08-13 19:59
I think this is a duplicate of https://github.com/inveniosoftware/invenio-records-resources/issues/41 . If so we can close.

**Comment by fenekku** [comment] 2020-09-01 18:16
Closing as duplicate (open back if not!)

**Closed by fenekku** 2020-09-01 18:16 UTC
